"""Shared I/O helpers for core/ and utils/ scripts.

core/ scripts import this directly (same-directory import -- works both
locally and after condor's transfer_Input_Files drops this file into the
worker sandbox alongside the main script, as long as it's added to that
script's transfer list; see build_transfer_files/COMMON_TRANSFER_FILES
below).

utils/ scripts (never shipped to condor, always run from the repo
checkout) reach it with a small path bootstrap first:

    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'core'))
    from io_utils import ...
"""
import getpass
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Union

import pandas as pd

# Shared strict-mode header for the condor worker bash scripts generated by
# submit/submit_*.py. Without this, a failed xrdcp or a crashing python worker
# lets the script fall through to its trailing cleanup/echo lines and exit 0,
# so condor (and downstream stages) see a "successful" job that delivered
# nothing. `set -e` makes any failing command abort the script immediately
# with a non-zero exit code instead.
BASH_STRICT_HEADER = "set -euo pipefail\n"


def eos_base_dir(username: Optional[str] = None) -> Path:
    """/eos/user/<first-letter>/<username> -- the implicit base every
    submit script's relative -d/-o path arguments are resolved against."""
    username = username or getpass.getuser()
    return Path(f'/eos/user/{username[0]}/{username}')


# Files every condor-transferred core/ script depends on beyond its own
# source file. Extend this list as io_utils.py grows more dependencies
# (e.g. if it starts importing another shared module).
COMMON_TRANSFER_FILES = ['core/io_utils.py']


def build_transfer_files(worker_script: str, *extra_paths: Union[str, Path]) -> str:
    """Builds a condor transfer_Input_Files value for a core/ worker script.

    Validates that every referenced file actually exists before submission,
    so a missing dependency fails loudly at submit time instead of deep
    inside a condor job's stderr log.
    """
    files = [f'core/{worker_script}', *COMMON_TRANSFER_FILES,
             *(Path(p).as_posix() for p in extra_paths)]
    missing = [f for f in files if not Path(f).is_file()]
    if missing:
        raise FileNotFoundError(f"transfer_Input_Files references missing file(s): {missing}")
    return ", ".join(files)


def discover_time_dirs(mother_dir: Union[str, Path]) -> List[Path]:
    """Resolves an apply_tdc_cuts.py (step 10) output location to the list of
    time-group directories to process.

    If `mother_dir` itself looks like a specific time-group folder (its name
    contains 'time'), returns just [mother_dir]. Otherwise scans its children
    for directories containing 'time' in the name; if both a bare 'time'
    folder and 'time_group*' folders are present (e.g. from reprocessing the
    same output location with different --partitions across separate runs),
    the bare folder is excluded so its events aren't double-counted against
    the group split.
    """
    mother_dir = Path(mother_dir)
    if 'time' in mother_dir.name:
        return [mother_dir]

    all_time_dirs = sorted(d for d in mother_dir.iterdir() if d.is_dir() and 'time' in d.name)
    has_groups = any('group' in d.name for d in all_time_dirs)
    if not has_groups:
        return all_time_dirs

    time_dirs = [d for d in all_time_dirs if 'group' in d.name]
    excluded = set(all_time_dirs) - set(time_dirs)
    if excluded:
        logging.warning(
            f"Detected split groups in {mother_dir}; excluding base folder(s) to avoid "
            f"double-counting: {sorted(d.name for d in excluded)}"
        )
    return time_dirs


def _warn_if_exists(path: Path) -> None:
    if path.exists():
        prev_mtime = datetime.fromtimestamp(path.stat().st_mtime)
        logging.warning(f"Overwriting existing output: {path} (previous mtime: {prev_mtime})")


def write_parquet(df: pd.DataFrame, path: Union[str, Path], **kwargs) -> None:
    """df.to_parquet, but logs a warning instead of silently clobbering a
    pre-existing output (e.g. left over from an earlier, possibly buggy,
    run of the same stage). Passes kwargs straight through -- callers keep
    specifying index=False etc. exactly as they did before."""
    path = Path(path)
    _warn_if_exists(path)
    df.to_parquet(path, **kwargs)


def write_csv(df: pd.DataFrame, path: Union[str, Path], **kwargs) -> None:
    """df.to_csv, with the same overwrite warning as write_parquet."""
    path = Path(path)
    _warn_if_exists(path)
    df.to_csv(path, **kwargs)
